### PR TITLE
Flat-footed -> Offguard

### PR DESCRIPTION
**Pull request by ChasarooniZ**

### CODE REVIEW

**Review by CydGoblin — COMMENTED** [review]
I would suggest updating the label to F is for Off-Guard

**Comment by roxim5** [comment]
This might fix #18 . Created the issue just to tie it to the PR

**Comment by Drental** [comment]
> I would suggest updating the label to F is for Off-Guard

the label is keybind menagerie already :D
Just won't change the ID, because that gotta be a hassle.

**Comment by CydGoblin** [comment]
I think this maybe wrong, the condition is named `off-guard`, with a `-`. Can someone confirm it is working?

**Comment by CydGoblin** [comment]
Definitely is no working for me, made a new PR  https://github.com/Drental/foundryvtt-pf2e-f-is-for-flatfooted/pull/19. If it works for others, feel free to reject.

**Pull request merged**
