### PR TITLE
Simplifies the condition setting a bit

### PR DESCRIPTION
**Pull request by xdy**
by replacing the cut and pasted conditions at the end with a loop over all fp2e conditions.

### CODE REVIEW

**Comment by xdy** [comment]
I had code to set a unique keybinding for each condition, but left it out as the keybindings I mapped didn't work, possibly due to https://gitlab.com/foundrynet/foundryvtt/-/issues/6344, or due to my own mistakes. :)
Anyway, once V9 stable is out it might be worth checking if something like this is useful:
```
	let modifierKeysArray = ["", "Shift", "Alt", "Control", "Shift + Alt", "Shift + Control", "Alt + Control", "Shift + Alt + Control"];
	let allowedKeys = " B E G H I J K L N O P Q R U X Y".split(" ").join(",Key").split(",").slice(1);
	let conditions = Object.keys(CONFIG.PF2E.conditionTypes);
	let counter = 0;
	for (let modifierkey = 0; modifierkey < modifierKeysArray.length; modifierkey++) {
		for (let fkey = 0; fkey < allowedKeys.length; fkey++) {
			let keycombo = modifierKeysArray[modifierkey] + (modifierKeysArray[modifierkey] === "" ? allowedKeys[counter % allowedKeys.length] : " + " + allowedKeys[counter % allowedKeys.length]);
			let condition = conditions[counter++];

			if (condition) {
				game.keybindings.register("pf2e-f-is-for-flatfooted", condition, {
					name: "Toggle " + condition,
					hint: "Changes the " + condition + " state of the selected or assigned Token",
					editable: [
						{
							key: keycombo
						}
					],
					onDown: () => {
						[canvas.tokens.controlled[0]?.actor ?? game.user.character].filter((actor) => actor)[0].toggleCondition(condition)
					},
				});
			}
		}
	}
```

**Comment by Drental** [comment]
well, I conflict on this hard now.

anyway, I don't think adding unfriendly and the likes would help any here, if anything it should be a stripped down list with the information if it's a condition with a value or not.
adding a Keybind is neat, but I deliberateley decided against it. If you can make that optional or have a maacro "fix" the keybinds I'd be all ears.

**Comment by shemetz** [comment]
I think this idea would make the code a lot neater, though if it's done I'd rather have it either use a specific predefined list of actions+effects, or use a predefined list of things not to include (e.g. unfriendly) and include everything else from the system's list.

Also, yes, better to wait until the conflict from https://github.com/Drental/foundryvtt-pf2e-f-is-for-flatfooted/pull/3 resolves too.

**Comment by xdy** [comment]
I'll make a new PR rather than rebase this one.

**Pull request closed without merging**
